import { StyleSheet } from 'react-native';

const SEARCH_INPUT_WIDTH = '80%';

export const styles = StyleSheet.create({
  container: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  searchContainer: {
    position: 'absolute',
    width: SEARCH_INPUT_WIDTH,
    alignSelf: 'center',
    zIndex: 999,
  },
  routeInfoCard: {
    position: 'absolute',
    top: 140,
    alignSelf: 'center',
    backgroundColor: 'white',
    paddingVertical: 15,
    paddingHorizontal: 25,
    borderRadius: 20,
    shadowColor: '#007AFF',
    shadowOpacity: 0.25,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 15,
    elevation: 10,
    zIndex: 998,
    minWidth: 240,
    alignItems: 'center',
  },
  routeInfoTitle: {
    fontWeight: '700',
    fontSize: 18,
    marginBottom: 6,
    color: '#007AFF',
  },
  routeInfoText: {
    fontSize: 16,
    color: '#333',
  },
  buttonContainer: {
    width: '100%',
    padding: 15,
    backgroundColor: '#fff',
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowOffset: { width: 0, height: -5 },
    shadowRadius: 10,
    elevation: 12,
  },
  buttonGroup: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 15,
  },
  btnSelect: {
    flex: 1,
    backgroundColor: '#e0e5ec',
    marginHorizontal: 8,
    paddingVertical: 14,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#aaa',
    shadowOpacity: 0.4,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 6,
    elevation: 6,
  },
  btnActive: {
    backgroundColor: '#000',
    shadowColor: '#000',
    shadowOpacity: 0.7,
    shadowRadius: 12,
  },
  btnSelectText: {
    fontSize: 16,
    color: '#555',
    fontWeight: '600',
  },
  btnActiveText: {
    color: '#fff',
    fontWeight: '700',
  },
  btnRemove: {
    flex: 1,
    backgroundColor: '#FF3B30',
    marginHorizontal: 8,
    paddingVertical: 14,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#FF3B30',
    shadowOpacity: 0.7,
    shadowRadius: 12,
    elevation: 8,
  },
  btnRemoveText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#fff',
  },
  modeButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 15,
  },
  modeBtn: {
    backgroundColor: '#e0e5ec',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 15,
    marginHorizontal: 5,
    shadowColor: '#aaa',
    shadowOpacity: 0.4,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 6,
    elevation: 4,
  },
  modeBtnActive: {
    backgroundColor: '#000',
    shadowColor: '#000',
    shadowOpacity: 0.7,
    shadowRadius: 10,
  },
  modeBtnText: {
    fontWeight: '600',
    color: '#555',
    fontSize: 14,
  },
  modeBtnTextActive: {
    color: '#fff',
    fontWeight: '700',
  },
  showCoordsBtn: {
    backgroundColor: '#000',
    paddingVertical: 14,
    borderRadius: 25,
    marginHorizontal: 60,
    marginBottom: 15,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.8,
    shadowRadius: 15,
    elevation: 8,
  },
  showCoordsBtnText: {
    color: 'white',
    fontWeight: '700',
    fontSize: 16,
  },
});

export const autoCompleteStyles = {
  container: {
    flex: 0,
    position: 'absolute',
    width: SEARCH_INPUT_WIDTH,
    alignSelf: 'center',
    zIndex: 999,
  },
  textInput: {
    height: 48,
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingHorizontal: 15,
    fontSize: 16,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
    width: '100%',
  },
  listView: {
    backgroundColor: 'white',
    borderRadius: 12,
    elevation: 5,
    zIndex: 999,
  },
};

export const customMapStyle = [
  {
    featureType: 'poi',
    elementType: 'labels',
    stylers: [{ visibility: 'off' }],
  },
  {
    featureType: 'transit',
    elementType: 'labels.icon',
    stylers: [{ visibility: 'off' }],
  },
  {
    featureType: 'road',
    elementType: 'geometry.stroke',
    stylers: [{ color: '#b0c4de' }],
  },
];