import {StyleSheet} from 'react-native';
import {BLACK, THEME_COLOR, WHITE, GREEN, BUTTON_COLOR} from '../../constants/colors';
import {ROBOTO, ROBOTO_BOLD} from '../../constants/fonts';

export default StyleSheet.create({
  cardView: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: WHITE,
    padding: 20,
    borderRadius: 20,
    marginHorizontal: 16,
    marginVertical: 10,
    shadowColor: BLACK,
    shadowOffset: {width: 0, height: 6},
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 8,
  },
  iconContainer: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: THEME_COLOR + '20', // translucent theme color
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoContainer: {
    flex: 1,
    marginLeft: 15,
  },
  header: {
    fontSize: 18,
    fontFamily: ROBOTO_BOLD,
    color: BLACK,
    marginBottom: 4,
  },
  itemText: {
    fontSize: 14,
    fontFamily: ROBOTO,
    color: GREEN,
    marginBottom: 2,
  },
  requestText: {
    fontSize: 16,
    fontFamily: ROBOTO_BOLD,
    color: THEME_COLOR,
    marginTop: 4,
  },
  badge: {
    backgroundColor: BUTTON_COLOR,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    alignSelf: 'flex-start',
    marginTop: 5,
  },
  badgeText: {
    color: WHITE,
    fontSize: 12,
    fontFamily: ROBOTO_BOLD,
  },
  rowBack: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    paddingRight: 15,
  },
  deleteButton: {
    backgroundColor: '#FF4D4D',
    justifyContent: 'center',
    alignItems: 'center',
    width: 70,
    height: 70,
    borderRadius: 20,
    marginTop: 10,
  },
  deleteButtonCard: {
    backgroundColor: '#FF4D4D',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 10,
  },
  deleteText: {
    color: WHITE,
    fontWeight: 'bold',
    fontSize: 14,
  },
  
  floatingButton: {
    backgroundColor: THEME_COLOR,
    width: 70,
    height: 70,
    borderRadius: 35,
    position: 'absolute',
    bottom: 25,
    right: 25,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: BLACK,
    shadowOffset: {width: 0, height: 6},
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 10,
  },
  floatingText: {
    color: WHITE,
    fontSize: 40,
    fontFamily: ROBOTO_BOLD,
  },
});
